/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darkneees_mobilerobotcv_nativeLib_ImageLib */

#ifndef _Included_com_darkneees_mobilerobotcv_nativeLib_ImageLib
#define _Included_com_darkneees_mobilerobotcv_nativeLib_ImageLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darkneees_mobilerobotcv_nativeLib_ImageLib
 * Method:    helloNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_darkneees_mobilerobotcv_nativeLib_ImageLib_helloNative
  (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif
#endif
